apiVersion: v1
kind: Service
metadata:
  name: parking-management-service
spec:
  type: NodePort
  selector:
    app: parking-management
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007 # This is the port that will be exposed on the host
